import { Translation } from './types';

export const TRANSLATIONS: Record<'en' | 'ar', Translation> = {
  en: {
    nav: {
      home: 'Home',
      solution: 'Solution',
      chat: 'AI Chat',
    },
    home: {
      heroTitle: 'Mindro-V1',
      heroSubtitle: 'Empowering Memory, Enhancing Life.',
      problemTitle: 'The Challenge',
      problemDesc: 'Early-stage Alzheimer’s creates gaps in daily memory, leading to confusion and loss of independence.',
      ideaTitle: 'The Idea',
      ideaDesc: 'A non-intrusive wearable that acts as a second brain, whispering context when you need it most.',
      solutionPreviewTitle: 'Meet Mindro-V1',
      featuresTitle: 'Key Features',
      targetUsersTitle: 'Designed For',
    },
    solution: {
      title: 'The Mindro-V1 Solution',
      whatIs: 'What is Mindro-V1?',
      howItWorks: 'How It Works',
      tech: 'Technologies',
      different: 'Why It’s Different',
    },
    chat: {
      title: 'Mindro Assistant',
      placeholder: 'Ask me anything...',
      welcome: 'Hello. How can I support your memory today?',
      suggestion1: 'Remind me about my schedule.',
      suggestion2: 'Who is in this photo?',
    },
    auth: {
      login: 'Log In',
      signup: 'Sign Up',
      profile: 'My Profile',
      email: 'Email Address',
      password: 'Password',
      name: 'Full Name',
      submitLogin: 'Access Account',
      submitSignup: 'Create Account',
      logout: 'Log Out',
      welcomeBack: 'Welcome Back',
    },
    settings: {
      title: 'Settings',
      language: 'Language',
      theme: 'Theme',
      notifications: 'Notifications',
      privacy: 'Privacy & Security',
      deleteAccount: 'Delete Account',
    },
  },
  ar: {
    nav: {
      home: 'الرئيسية',
      solution: 'الحل',
      chat: 'محادثة AI',
    },
    home: {
      heroTitle: 'مايندرو-V1',
      heroSubtitle: 'تمكين الذاكرة، تعزيز الحياة.',
      problemTitle: 'التحدي',
      problemDesc: 'يسبب مرض الزهايمر في مراحله المبكرة فجوات في الذاكرة اليومية، مما يؤدي إلى الارتباك وفقدان الاستقلالية.',
      ideaTitle: 'الفكرة',
      ideaDesc: 'جهاز قابل للارتداء غير تطفلي يعمل كعقل ثانٍ، يهمس بالسياق عندما تكون في أمس الحاجة إليه.',
      solutionPreviewTitle: 'تعرف على مايندرو-V1',
      featuresTitle: 'الميزات الرئيسية',
      targetUsersTitle: 'صمم لـ',
    },
    solution: {
      title: 'حل مايندرو-V1',
      whatIs: 'ما هو مايندرو-V1؟',
      howItWorks: 'كيف يعمل',
      tech: 'التقنيات المستخدمة',
      different: 'لماذا هو مختلف',
    },
    chat: {
      title: 'مساعد مايندرو',
      placeholder: 'اسألني أي شيء...',
      welcome: 'مرحبًا. كيف يمكنني دعم ذاكرتك اليوم؟',
      suggestion1: 'ذكرني بجدولي.',
      suggestion2: 'من في هذه الصورة؟',
    },
    auth: {
      login: 'تسجيل الدخول',
      signup: 'إنشاء حساب',
      profile: 'ملفي الشخصي',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      name: 'الاسم الكامل',
      submitLogin: 'دخول',
      submitSignup: 'تسجيل',
      logout: 'تسجيل خروج',
      welcomeBack: 'أهلاً بك',
    },
    settings: {
      title: 'الإعدادات',
      language: 'اللغة',
      theme: 'السمة',
      notifications: 'الإشعارات',
      privacy: 'الخصوصية والأمان',
      deleteAccount: 'حذف الحساب',
    },
  },
};